import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Providers } from "./providers/provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ToastContainer } from 'react-toastify';
import { ourFileRouter } from "@/app/api/uploadthing/core";
import 'react-toastify/dist/ReactToastify.css';
const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bookmark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
        <ToastContainer />
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        {children}
        </Providers>
        </body>
    </html>
  );
}
